platform :ios, 11.0
use_frameworks!
inhibit_all_warnings!

target 'ReactiveBluetooth_Example' do
  pod 'ReactiveBluetooth', :path => '../'

  pod 'Swinject'

  target 'ReactiveBluetooth_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
